spring:
  application:
    name: Product Service

server:
  port: 8080

management:
  server:
    port: 8081
  info:
    git:
      mode: full

services:
  redSky:
    baseUrl: https://redsky-uat.perf.target.com
    productDetails: ${services.redSky.baseUrl}/redsky_aggregations/v1/redsky/case_study_v1
    key: 3yUxt7WltYG7MFKPp7uyELi1K40ad2ys