spring:
  application:
    name: Product Service
  data:
    cassandra:
      username: root
      password: root
      port: 9042
      contactPoints: 127.0.0.1
      keySpaceName: prices
      schemaAction: CREATE_IF_NOT_EXISTS
datastax-java-driver:
  basic:
    request:
      timeout: 20 seconds
server:
  port: 8080

management:
  server:
    port: 8081
  info:
    git:
      mode: full

services:
  redSky:
    baseUrl: https://redsky-uat.perf.target.com
    productDetails: ${services.redSky.baseUrl}/redsky_aggregations/v1/redsky/case_study_v1
    key: 3yUxt7WltYG7MFKPp7uyELi1K40ad2ys